### ISSUE TITLE
Touch tolerance

### ISSUE THREAD

**Issue by shakram02** [shakram02/PiFloor#18]
Make the rectangles in the calibration mode more tolerant in touch. Edit [this](https://github.com/shakram02/EdGrid/blob/9299b675fa51dbb45865cbe33db5661eeea91b51/app/src/main/java/ocrreader/graphcis/OcrGraphic.kt#L49) code

**Comment by AhmedMaghawry** [comment]
Ok, get it

**Comment by shakram02** [comment]
@AhmedMaghawry this is fixed?

**Comment by AhmedMaghawry** [comment]
Yes
