### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by shakram02** [shakram02/PiFloor#36]
PiFloor is logo-less :cry: 
The logo needs to be displayed in the Android and the web interface

**Comment by mirzazulfan** [comment]
Hi @shakram02 I am a graphic designer, i've designed a logo for your great project. what do you think?
![pifloor](https://user-images.githubusercontent.com/36124339/55612213-ec7db500-57b1-11e9-9630-34b1101772a8.png)

**Comment by shakram02** [comment]
Selamat datang di Pifloor, terima kasih untuk "effort" andah, please pardon my Indonesian, I just learnt a little while visiting Indonesia :heart: 

What do you think about using a font that looks like a sketch drawing a little bit?
Can you please tell me the philosophy behind the logo? (I understand the question mark, but I don't really understand what's inside it)

**Comment by mirzazulfan** [comment]
@shakram02 Thanks for your response, The idea of ​​logo is the question mark that forms 'Pi' and students who are discussing. If you need something else, I'll change it. Terima kasih atas sambutan saudara :)

**Comment by shakram02** [comment]
sama sama :pray: 
I see, that's interesting, what about changing the P to be included in the inner circle (so you'll basically wrap the question mark the other way around) and just draw a bar to represent the ***i**, the image I posted is just another possibility.

What about adding some sort of hands to the students? so that they appear as if they're collaborating (I'm not sure which hand to choose, maybe just a small circle but I'm not sure)

I think the text can be changed to look a bit more suited for children? (less than 13) what do you think?

![image](https://user-images.githubusercontent.com/10996982/55648968-fa4b2e80-57e1-11e9-8e26-548b59011e9b.png)

**Comment by mirzazulfan** [comment]
Something like this ? what do you think?
![pi](https://user-images.githubusercontent.com/36124339/55680826-22a16d00-5949-11e9-9bae-98e63a0b0287.png)

**Comment by shakram02** [comment]
I think the first one is pretty nice, what do you think about the font? can it become more childish maybe? I suggest that you add an effect like a crayon or something like this, what do you think?
![image](https://user-images.githubusercontent.com/10996982/55687620-47a8d680-596f-11e9-8380-d97dbbceb1c6.png)

**Comment by mirzazulfan** [comment]
I agree with you @shakram02 . I made some variation of logotype and logomark. which one do you like?
![piflooor](https://user-images.githubusercontent.com/36124339/55717693-10e0c800-5a24-11e9-84f2-80cba60f98ee.png)

**Comment by shakram02** [comment]
That's very neat :ok_hand: :ok_hand: 
I like no.3 the most, is it possible if you choose a darker tone of yellow? so it has some contrast with white? or put the logo in some sort of bounding box so it can be used anywhere easily?

For the logo I guess material design will suffice (not flat, so I guess it's better without a shadow)

If you're interested in material UI design (just design for Android -no coding needed-) please tell me :muscle: 
terima kasih banyak :pray:

**Comment by mirzazulfan** [comment]
Hi @shakram02 I've created a pr #90 and upload the files. Yo can doanload all editables files [here](https://drive.google.com/drive/folders/1iYvghyi0uSdQescZ6kdZB54Nm95CnOhU) , I don't understand about material UI design. :) Semoga sukses saudara. Best Regard!
