### ISSUE TITLE
Move questions editing, download to a separate page

### ISSUE THREAD

**Issue by shakram02** [shakram02/PiFloor#66]
I think it might be better to put everything related to question editing in a separate page. The main menu of the teacher should include 3 items only. The following organization is suggested

- Play
- Upload questions
- Compose questions
   - Add questions
   - Edit existing
   - Download questions

**Comment by ahmedhammad97** [comment]
Let me make sure I understand.
Do you mean by "separate page" a different route, or just a different modal?
Currently we are showing a modal for "Add questions" and "Edit existing" together, would adding "Download questions" to this modal instead of being on home page solve the issue?

**Comment by shakram02** [comment]
> Do you mean by "separate page" a different route, or just a different modal?

A different route, I think it's more suitable (as UX) to edit questions in a separate web page rather than a pop up

> would adding "Download questions" to this modal instead of being on home page solve the issue?

no
