### ISSUE TITLE
Red highlight on game grid item?

### ISSUE THREAD

**Issue by shakram02** [shakram02/PiFloor#68]
There was a right highlight displayed when the answer is selected. Red generally includes that something wrong has happened. Any selected answer highlights its tile in red (in the game grid)

**Comment by ahmedhammad97** [comment]
Actually I thought we should try to get the footstep image to work instead of just coloring the background, so I tested the built files on a local server at the image was served whenever a socket message is received.
Should we also do the background coloring?

**Comment by shakram02** [comment]
I guess changing the background color will be enough, we don't need to use an image for foot steps
(because maybe in a case the answer text will be large and will overlap the image)
